name: Deploy to AWS Lambda (Python 3.13)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r lambda/requirements.txt

    - name: Package Lambda function
      run: |
        mkdir -p python
        zip -r ../function.zip .

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name lambda_handler \
          --zip-file fileb://lambda.zip \
          --publish